INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('lot balonem', 16);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('zwiedzanie', 15);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('bar', 18);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('teatr', 10);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('lot balonem', 20);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('dyskoteka', 13);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('muzeum', 14);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('zwiedzanie', 14);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('lot balonem',  7);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('bar',  7);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('sesja zdjeciowa',  8);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('teatr',  7);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('zoo',  9);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('sesja zdjeciowa',  7);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('bar', 16);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('sesja zdjeciowa',  3);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('bar', 14);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('zoo', 20);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('zwiedzanie',  5);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('lot balonem', 13);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('zoo', 16);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('teatr', 13);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('zoo',  4);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('dyskoteka',  9);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('muzeum',  9);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('teatr', 18);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('dyskoteka', 17);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('muzeum', 20);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('dyskoteka',  5);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('bar',  2);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('kregle',  9);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('kregle', 15);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('teatr',  1);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('lot balonem', 11);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('kino', 16);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('basen',  3);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('basen',  6);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('zoo',  3);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('muzeum',  8);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('lot balonem',  8);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('lot balonem', 12);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('zwiedzanie', 16);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('kino',  8);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('teatr', 17);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('sesja zdjeciowa', 12);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('sesja zdjeciowa', 17);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('muzeum',  7);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('bar', 11);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('dyskoteka',  7);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('dyskoteka',  4);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('kino', 13);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('zwiedzanie',  7);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('lot balonem',  6);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('kregle', 18);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('sesja zdjeciowa',  4);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('teatr',  9);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('kino',  6);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('zoo',  2);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('basen', 13);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('teatr', 11);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('kregle', 17);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('teatr', 20);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('dyskoteka', 10);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('zoo', 18);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('teatr',  6);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('bar', 17);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('kino', 18);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('muzeum', 16);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('dyskoteka',  3);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('zwiedzanie',  8);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('dyskoteka',  2);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('kino', 19);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('lot balonem',  9);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('basen', 18);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('zwiedzanie', 11);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('kregle',  4);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('lot balonem',  2);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('muzeum', 15);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('basen',  2);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('kregle', 10);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('bar',  8);
