INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('hotel',  3);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('morze', 10);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('samolot',  6);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('duze miasto',  4);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('autokar', 19);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('autokar',  5);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('hotel', 12);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('widoki', 13);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('kasyna', 20);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('autokar',  9);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('duze miasto',  9);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('autokar',  2);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('samolot',  4);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('samolot',  3);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('morze',  5);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('hotel', 16);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('duze miasto', 10);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('hotel',  7);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('widoki',  2);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('autokar', 14);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('widoki',  1);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('samolot',  9);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('widoki',  5);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('gory',  7);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('morze', 18);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('plaza',  5);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('hotel', 11);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('samolot', 19);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('morze', 11);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('samolot',  8);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('kasyna',  5);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('hotel',  1);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('samolot', 11);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('widoki', 18);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('gory', 16);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('morze', 13);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('duze miasto',  2);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('widoki', 20);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('duze miasto', 15);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('morze', 17);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('hotel', 10);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('hotel',  2);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('autokar',  7);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('samolot',  5);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('gory',  1);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('kasyna',  2);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('hotel',  4);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('samolot',  2);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('kasyna',  4);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('widoki', 14);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('gory',  4);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('autokar',  3);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('kasyna', 17);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('plaza',  6);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('autokar',  6);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('widoki',  7);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('duze miasto', 11);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('plaza', 14);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('hotel',  8);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('kasyna', 10);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('plaza', 19);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('samolot',  1);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('duze miasto',  6);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('morze',  7);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('plaza', 16);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('kasyna', 12);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('gory',  3);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('plaza',  4);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('morze', 14);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('plaza',  2);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('plaza', 13);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('morze',  1);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('duze miasto', 17);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('kasyna', 18);
INSERT INTO tagi_ofert (tag, oferta_id) VALUES ('gory', 19);
