INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('teatr', 17);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('kregle',  3);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('kino',  3);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('dyskoteka', 20);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('lot balonem',  3);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('zwiedzanie',  5);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('zwiedzanie',  2);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('muzeum', 11);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('teatr', 18);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('lot balonem', 13);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('muzeum',  1);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('basen', 13);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('basen', 14);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('zoo', 19);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('bar', 12);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('sesja zdjeciowa',  3);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('muzeum', 10);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('zoo',  2);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('kino',  1);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('teatr',  6);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('lot balonem',  9);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('lot balonem',  1);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('zwiedzanie', 16);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('dyskoteka', 11);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('sesja zdjeciowa',  5);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('basen',  1);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('lot balonem',  6);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('dyskoteka', 16);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('zwiedzanie', 13);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('zoo',  5);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('zwiedzanie',  6);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('bar',  8);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('dyskoteka', 17);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('zoo', 10);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('dyskoteka',  3);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('basen', 17);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('lot balonem', 17);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('kregle',  7);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('zwiedzanie',  7);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('teatr',  5);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('kino',  8);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('bar',  6);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('sesja zdjeciowa', 11);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('kino', 13);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('zwiedzanie', 10);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('muzeum',  6);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('kregle', 19);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('kregle', 12);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('muzeum',  3);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('lot balonem', 11);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('basen', 10);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('zwiedzanie', 14);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('kino',  4);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('sesja zdjeciowa', 13);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('basen',  4);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('sesja zdjeciowa', 16);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('basen',  6);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('bar', 15);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('kregle', 17);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('lot balonem', 15);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('kino', 15);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('zoo', 12);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('basen', 16);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('dyskoteka', 15);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('zwiedzanie', 12);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('bar', 17);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('bar', 13);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('kregle', 20);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('kino',  9);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('dyskoteka',  2);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('zoo', 17);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('dyskoteka',  4);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('dyskoteka',  1);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('zwiedzanie',  3);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('zoo', 14);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('sesja zdjeciowa',  6);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('sesja zdjeciowa',  1);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('sesja zdjeciowa', 19);
INSERT INTO atrakcje_w_ofercie (atrakcja, oferta_id) VALUES ('zwiedzanie',  4);
